### PR TITLE
PHP spacing

### LINKED ISSUE #72: No space before/after Square bracket
### What you would like to change/add
I propose that we use no spaces at the start and the end of Square Brackets.

### Why you would like to change/add this
In my opinion, because it is interacting with the object/variable to the left of the square brackets, it shouldn't have a space to clearly show that is it is all in part with that object/variable. 

### Examples
This:
```php
$data[$key]
```
Not:
```php
$data[ $key ]
```

This:
```php
$form->is_form_visible_customer = isset($data['is_form_visible_customer']) ? ($data['is_form_visible_customer'] == 'on' ? 1 : 0) : 0;
```
Not:
```php
$form->is_form_visible_customer = isset($data[ 'is_form_visible_customer' ]) ? ($data[ 'is_form_visible_customer' ] == 'on' ? 1 : 0) : 0;
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

* [Langley Foxall](https://langleyfoxall.co.uk) - The Langley Foxall website

### LINKED ISSUE #74: Spaces in string concatenation
### What you would like to change/add

Since we have started to adopt StyleCI I have been working on creating a standard configuration for our Laravel projects. One thing I noticed is that StyleCI likes to remove spaces in string concatenation and, as far as I am aware, we have no internal style guide for it and PSR has no defined standard for it either.

We can either enforce there to be spaces or enforce no spaces.

### Why you would like to change/add this

I personally think that we should have spaces since it improves readability, especially if there are multiple variables.

### Examples

**concat_without_spaces**
```php
return $this->first_name . ' ' . $this->last_name;
```
would then become:
```php
return $this->first_name.' '.$this->last_name;
```

**concat_with_spaces**
```php
return $this->first_name.' '.$this->last_name;
```
would then become:
```php
return $this->first_name . ' ' . $this->last_name;
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

👍 for with spaces.
👎 for without spaces.

### PR DESCRIPTION
**Pull request by DivineOmega**
This PR adds content regarding two previously discussed points related to PHP spacing.

Closes #72.
Closes #74.

### CODE REVIEW

**Comment by dextermb** [comment]
@DivineOmega something that seems to be popping up in a currently project is the spacing of multiline objects/arrays.

For example:
```php
// 2 spaces
$arr = [
  'hello',
  'world
];
```

```php
// 4 spaces
$arr = [
    'hello',
    'world
];
```

I feel like either one of these should be defined here too. In PHPStorm this setting is called _line continuation_ or something similar.

**Comment by DivineOmega** [comment]
@dextermb Sounds like a good idea to include this as well. I'd probably go with 4 spaces here too, personally. Feel free to PR my PR. If not, I'll get this in at some point. :+1:

**Comment by dextermb** [comment]
> I'd probably go with 4 spaces here too

I agree

**Comment by AlexCatch** [comment]
I'd go with 2 spaces personally, 4 here just seems like way too much whitespace.

**Comment by ash123456789** [comment]
It would be ideal to stick with 4 spaces across the board for PHP.

**Pull request merged**
