### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by DivineOmega**
This PR simply replaces the Fox emoji with a small version of the Langley Foxall logo.

### CODE REVIEW

**Comment by ash123456789** [comment]
Just a minor thing but it might look better if the logo was centralised (along with the text) with the text underneath the logo?

Example (obviously needs improvements):

<p align="center">
  
<br>
Langley Foxall Technologies
</p>

**Comment by dextermb** [comment]
On a side note, when creating new branches we should start using our naming conventions.
https://github.com/langleyfoxall/technologies/pull/1#issuecomment-419371619

**Comment by DivineOmega** [comment]
Made a few adjustments. Here's what it look like now:

new readme format with logo

**Comment by dextermb** [comment]
`p` tag with a `img` and header tag inside it 😨

**Comment by DivineOmega** [comment]
> `p` tag with a `img` and header tag inside it

Swapped out to a `div`.

**Comment by wheatleyjj** [comment]
That was ALOT of commotion for a logo gents.

**Pull request merged**
