### PR TITLE
[WIP] Add DevOps folder and start Git Workflow Documentation

### PR DESCRIPTION
**Pull request by wheatleyjj**
Restructured the project to give DevOps it's own section - moved CloudFlare with it.

Under this new section started developing the Git Workflow following discussions here: https://github.com/langleyfoxall/technologies/pull/1 . It needs a lot of work/input but it's late and I need some sleep.

Happy for initial comments/additions/suggestions from all.

### CODE REVIEW

**Comment by dextermb** [comment]
It should also be mentioned that commit messages are supposed to be descriptive and commands.
```
Add API Documentation
```

Not
```
Added API Documentation
```

Or
```
Update README
- Add API Documentation
```

Not
```
Update README
```

**Comment by wheatleyjj** [comment]
> It should also be mentioned that commit messages are supposed to be descriptive and commands.
> 
> ```
> Add API Documentation
> ```
> Not
> 
> ```
> Added API Documentation
> ```
> Or
> 
> ```
> Update README
> - Add API Documentation
> ```
> Not
> 
> ```
> Update README
> ```
> As seen [here](https://chris.beams.io/posts/git-commit/#imperative) along with other useful pointers

I've now added this to the flow. Anything else for a V1?

**Comment by dextermb** [comment]
@wheatleyjj Everything else looks okay for v1

**Comment by dextermb** [comment]
One thing I'd like to add is:

---

### Pull Requests

Only the person who created the pull request or higher management should merge it. Even though it may of been accepted by the reviewers the person who created it might of noticed a change after the fact or higher management might have a reason for delaying the merge.

**Comment by wheatleyjj** [comment]
@dextermb Added. Please approve if you agree for initial merge.

**Comment by DivineOmega** [comment]
@wheatleyjj Just added a link to your new DevOps page, as I noticed there didn't seem to be any way to access it.

**Comment by wheatleyjj** [comment]
Thanks @DivineOmega , I'd like to say this is a secret page, but I just missed it, it seems.

**Comment by DivineOmega** [comment]
Awesome. :+1:

**Pull request merged**
