### PR TITLE
Added GitFlow Document

### PR DESCRIPTION
**Pull request by wheatleyjj**

### CODE REVIEW

**Comment by DivineOmega** [comment]
I'm personally against using `master` to mean stable, as it is opposite to way in which the vast majority of GitHub projects are setup.

My preference would be:

* `master` for development
* `feature` branches created from `master`
* `staging`
* `production`

**Comment by AlexCatch** [comment]
I recommend we use GitFlow.

- ```master``` | The most recent published version of our docs (production)
- ```develop``` | The current development branch, contains merged feature branches
- ```feature``` | Feature branches are merged off of develop
- ```rc``` | Release candidate branches - hold a candidate for release (branched off from develop) for viewing, going over with the team and small additions before a stable release by merging with master.
- ```hotfix``` | Hotfix branches are for fixing critical or small issues in production (typos etc)

GitFlow is widely used and accepted & comes built in with GitKraken.

Additional information about this workflow can be found [here](https://datasift.github.io/gitflow/IntroducingGitFlow.html)

**Comment by wheatleyjj** [comment]
I suppose it goes to a vote then... 

@langleyfoxall/langley-foxall ??!!

**Comment by dextermb** [comment]
I personally tend to follow @DivineOmega method. 

- `master` for the latest changes (development), meaning it would be unstable
- `feature-*` or `feature/*` for new features
- `hotfix-*` or `hotfix/*` for fixes
- `staging` for a testing server where the client can look at things
- `production` for the production server

**Comment by AlexCatch** [comment]
I'm open to agreeing with @dextermb and @DivineOmega if we were to have master be production & a develop branch be where we keep the latest changes.

**Comment by wheatleyjj** [comment]
I suggest that we write up our own Git Workflow then that encapsulates this.
Happy to go with @dextermb 's comments above - I'd vote for foldered branches: `feature/`, `hotfix/`.

This could link into the GitHub Self Serve platform I intend on making with someone to scaffold these repositories properly.

**Comment by ash123456789** [comment]
I'd much prefer to use `feature/` instead of `feature-*` since it just looks cleaner in my opinion.

**Comment by wheatleyjj** [comment]
Continued this idea by starting git workflow documentation here: https://github.com/langleyfoxall/technologies/pull/10

**Pull request closed without merging**
