### PR TITLE
Update expo-quick-start.md

### PR DESCRIPTION
**Pull request by dextermb**
## Description
Fixes a typo

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds documentation)
- [ ] Breaking change (This is a significant change)

## Checklist

- [x] I have ensured that I have used relative links where appropriate.
- [x] I have proofread my documentation.

### CODE REVIEW

**Comment by dextermb** [comment]
:speaking_head_in_silhouette: Don't let your memes be dreams

**Comment by AlexCatch** [comment]
I think you can eject regardless of which workflow you select, I might be wrong but if that's the case, it might make sense mentioning that regardless of which flow you choose - you always have the option of ejecting.

**Comment by NilesB** [comment]
@AlexCatch That is mentioned `Managed Workflow projects can later be `detached` if you want to use native development environments`

**Comment by dextermb** [comment]
> I think you can eject regardless of which workflow you select, I might be wrong but if that's the case, it might make sense mentioning that regardless of which flow you choose - you always have the option of ejecting.

I am only resolving a typo in this pull request. Any other changes should be in another PR.

**Comment by AlexCatch** [comment]
@NilesB Ah didn't catch that - sweet 👍

**Pull request merged**
