### PR TITLE
Update web.md

### PR DESCRIPTION
**Pull request by dextermb**
- Add toubleshooting section
- Define issue with routing and protocols

### CODE REVIEW

**Comment by DivineOmega** [comment]
I like @ash123456789's idea of splitting this off into a troubleshooting page. We could have a troubleshoot page per platform.

I also think this might work well in a table form.

| Problem | Solution |
| ------------ | ----------- |
| I get a `MethodNotAllowedException` (`405`) even when my routes are defined properly, and when I go to a route that doesn't exist I get a `NotFoundException` (`404`). | Check that you are using the right protocol (`http/https`). |

**Comment by ash123456789** [comment]
@DivineOmega there could be multiple solutions per problem so I'm not sure if a table would be best. Unless we only list the most common solution?

**Comment by dextermb** [comment]
Definitely could go in another file, `troubleshoot.md` or something. 
A table layout could work, there would be many solutions to try though.

**Comment by dextermb** [comment]
@ash123456789 🎩 💼 Great minds think alike

**Comment by DivineOmega** [comment]
Perhaps a specific `laravel-troubleshooting.md` file?

**Comment by ash123456789** [comment]
Maybe another folder `web/troubleshooting/laravel.md`?

**Comment by DivineOmega** [comment]
Ack the issue with multiple solutions in a table layout. In a seperate file, heading can be used to seperate out the problems instead.

**Comment by wheatleyjj** [comment]
@dextermb any update on when this is going to be done?

**Comment by dextermb** [comment]
@wheatleyjj it'll be done eventually, just gotta make time to do it

**Comment by AlexCatch** [comment]
Any progress on this? It's becoming a pretty stale PR

**Pull request closed without merging**
